---
title: "Final Project - "
author: "Aaron Abromowitz, Stephanie Duarte, Dammy "
date: "2024-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# EDA
The first thing that is done when you get a dataset is to peform an Exploratory Data Anslysis, to see what characteristics the data has.

## Create training and test set
Going forward, we will use the training set for all analysis and model building.  The test set will be used at the end to get metrics for the various models we create.
```{r}
# Pull in data
data<-read.csv("C:/Users/aabro/OneDrive/Desktop/SMU Program/Classes/Stats 2/Final Project/bank-additional-full.csv",stringsAsFactors = T, sep=";")

# Set levels to use for later
data$y <- relevel(data$y, ref="yes")
data$month <- factor(data$month, levels=c('mar','apr','may','jun','jul','aug','sep','oct','nov','dec'))

# Create the train and test split
train_perc <- .8
set.seed(1234)
train_indices <- sample(nrow(data), floor(train_perc * nrow(data)))
train_data <- data[train_indices, ]
nrow(train_data)
test_data <- data[-train_indices, ] 
nrow(test)
train_data$duration <- c()
```

